# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
    - master

pool:
    vmImage: "ubuntu-latest"

variables:
    buildConfiguration: "Release"

steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: "dotnet build $(buildConfiguration)"

    - task: DotNetCoreCLI@2
      inputs:
          command: "test"
          projects: "**/*Test/*.csproj"
          arguments: "--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/"
          testRunTitle: "Run xUnit Tests"

    - task: PublishCodeCoverageResults@1
      displayName: "Publish code coverage report"
      inputs:
          codeCoverageTool: "Cobertura"
          summaryFileLocation: "$(Build.SourcesDirectory)/**/coverage.cobertura.xml"

    - task: DotNetCoreCLI@2
      displayName: "dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
      inputs:
          command: publish
          publishWebProjects: false
          projects: "src/SimpleAPI/SimpleAPI.csproj"
          arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
          zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: "publish artifacts"
